// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgcKR58ZedzlQa7DqMKwabhiI3THYd4uM',
    appId: '1:94563977861:web:9e28f05964e14414c277ec',
    messagingSenderId: '94563977861',
    projectId: 'waste-management-51d95',
    authDomain: 'waste-management-51d95.firebaseapp.com',
    storageBucket: 'waste-management-51d95.appspot.com',
    measurementId: 'G-135WCKSSYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wbz73QGSPwZayKxeDbrUhON0-2rGRfY',
    appId: '1:94563977861:android:f01c552b368c22bac277ec',
    messagingSenderId: '94563977861',
    projectId: 'waste-management-51d95',
    storageBucket: 'waste-management-51d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk66TTcaHBhZOjfEhXPIgmhpcry3waj-8',
    appId: '1:94563977861:ios:716e2b268525519ac277ec',
    messagingSenderId: '94563977861',
    projectId: 'waste-management-51d95',
    storageBucket: 'waste-management-51d95.appspot.com',
    androidClientId: '94563977861-tnfae5onnq42edm61bo9copc5jjgajfg.apps.googleusercontent.com',
    iosClientId: '94563977861-dssjv5hbtc6jda5n36psslbdahnejob9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk66TTcaHBhZOjfEhXPIgmhpcry3waj-8',
    appId: '1:94563977861:ios:716e2b268525519ac277ec',
    messagingSenderId: '94563977861',
    projectId: 'waste-management-51d95',
    storageBucket: 'waste-management-51d95.appspot.com',
    androidClientId: '94563977861-tnfae5onnq42edm61bo9copc5jjgajfg.apps.googleusercontent.com',
    iosClientId: '94563977861-dssjv5hbtc6jda5n36psslbdahnejob9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteManage',
  );
}
